spring:
  rabbitmq:
    addresses: ${rabbitmq_address}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个

    topic:
      auth-change: auth-change
      user-registered: user-registered
      outfit-recommend-completed: outfit-recommend-completed
      clothing-event: clothing-event
