spring:
  cloud:
    sentinel:
      transport:
        dashboard: ${SENTINEL_HOST}:${SENTINEL_DASHBOARD_PORT}
        port: ${SENTINEL_TRANSPORT_PORT}
      eager: true
      # Sentinel数据源配置 - 从Nacos动态加载规则
      datasource:
        # 流控规则数据源
        flow:
          nacos:
            server-addr: ${NACOS_HOST}:${NACOS_PORT}
            dataId: ${spring.application.name}-sentinel-flow.json
            namespace: ${NACOS_NAMESPACE}
            username: nacos
            password: nacos
            groupId: DEFAULT_GROUP
            rule-type: flow
            # 数据格式：JSON
            data-type: json
        # 降级规则数据源
        degrade:
          nacos:
            server-addr: ${NACOS_HOST}:${NACOS_PORT}
            dataId: ${spring.application.name}-sentinel-degrade.json
            namespace: ${NACOS_NAMESPACE}
            groupId: DEFAULT_GROUP
            rule-type: degrade
            username: nacos
            password: nacos
            # 数据格式：JSON
            data-type: json
