# 服务器配置
server:
  port: 9010  # 网关服务端口

spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
          globalcors:
            cors-configurations:
              '[/**]':
                allowedHeaders: '*'      # 允许所有请求头
                allowedMethods: '*'      # 允许所有 HTTP 方法
                allowedOrigins: '*'      # 允许所有来源（生产环境应限制）
          routes:
            # 认证服务路由
            - id: kaleido-auth-server
              uri: lb://kaleido-auth  # 负载均衡到认证服务
              predicates:
                - Path=/kaleido-auth/**  # 路径匹配规则

            # 用户服务路由
            - id: kaleido-user-server
              uri: lb://kaleido-user  # 负载均衡到用户服务
              predicates:
                - Path=/kaleido-user/**  # 路径匹配规则

            # 通知服务路由
            - id: kaleido-notice-server
              uri: lb://kaleido-notice  # 负载均衡到通知服务
              predicates:
                - Path=/kaleido-notice/**  # 路径匹配规则

            # 管理后台服务路由
            - id: kaleido-admin-server
              uri: lb://kaleido-admin  # 负载均衡到管理后台服务
              predicates:
                - Path=/kaleido-admin/**  # 路径匹配规则

            # 衣柜服务路由
            - id: kaleido-wardrobe-server
              uri: lb://kaleido-wardrobe  # 负载均衡到衣柜服务
              predicates:
                - Path=/kaleido-wardrobe/**  # 路径匹配规则
                
            # 标签服务后台服务路由
            - id: kaleido-tag-server
              uri: lb://kaleido-tag  # 负载均衡到标签服务
              predicates:
                - Path=/kaleido-tag/**  # 路径匹配规则

            # 金币服务路由
            - id: kaleido-coin-server
              uri: lb://kaleido-coin  # 负载均衡到金币服务
              predicates:
                - Path=/kaleido-coin/**  # 路径匹配规则             

            # 推荐服务路由
            - id: kaleido-recommend-server
              uri: lb://kaleido-recommend  # 负载均衡到推荐服务
              predicates:
                - Path=/kaleido-recommend/**  # 路径匹配规则

            # ai服务路由
            - id: kaleido-ai-server
              uri: lb://kaleido-ai  # 负载均衡到ai服务
              predicates:
                - Path=/kaleido-ai/**  # 路径匹配规则 

gateway:
  auth:
    # 认证策略列表
    strategies:
      # 公共路径（无需认证）
      - pattern: "/kaleido-auth/public/**"
        strategy: "PUBLIC"
        # 说明：认证服务的公共接口，如登录、注册等

      # 管理员认证路径
      - pattern: "/kaleido-admin/**"
        strategy: "ADMIN"
        # 说明：管理后台所有接口需要管理员权限

      - pattern: "/kaleido-notice/**"
        strategy: "ADMIN"
        # 说明：通知服务接口需要管理员权限

      # 用户认证路径
      - pattern: "/kaleido-tag/**"
        strategy: "USER"
        # 说明：用户服务接口需要用户登录

      # 用户认证路径
      - pattern: "/kaleido-coin/**"
        strategy: "USER"
        # 说明：用户服务接口需要用户登录

      # 用户认证路径
      - pattern: "/kaleido-wardrobe/**"
        strategy: "USER"
        # 说明：用户服务接口需要用户登录

      # 用户认证路径
      - pattern: "/kaleido-user/**"
        strategy: "USER"
        # 说明：用户服务接口需要用户登录
    
      # 用户认证路径
      - pattern: "/kaleido-recommend/**"
        strategy: "USER"
        # 说明：推荐服务接口需要用户登录

      # 用户认证路径
      - pattern: "/kaleido-ai/**"
        strategy: "USER"
        # 说明：推荐服务接口需要用户登录

    # 默认策略（当没有路径匹配时使用）
    default-strategy: "PUBLIC"