spring:
  cloud:
    nacos:
      server-addr: 10.4.135.208:8849
      discovery:
        namespace: 30d71fbd-2d24-4757-81f4-679d26f0ed93
      config:
        namespace: 30d71fbd-2d24-4757-81f4-679d26f0ed93
        file-extension: yaml
